# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('address', models.GenericIPAddressField(verbose_name='IP address')),
            ],
            options={
                'permissions': (('view_host', 'View Host'),),
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'permissions': (('view_host_group', 'View Host Groups'),),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
            options={
                'permissions': (('view_variable', 'View Variables'),),
            },
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='vars',
            field=models.ManyToManyField(related_name='host_groups', to='core.Variable', verbose_name='Variables'),
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(related_name='hosts', to='core.HostGroup', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='host',
            name='vars',
            field=models.ManyToManyField(related_name='hosts', to='core.Variable', verbose_name='Variables'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('name', 'address')]),
        ),
    ]
