# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('playbook', models.FilePathField(verbose_name='Playbook path')),
                ('host_groups', models.ManyToManyField(related_name='task_templates', to='core.HostGroup', verbose_name='HostGroups')),
                ('hosts', models.ManyToManyField(related_name='task_templates', to='core.Host', verbose_name='Hosts')),
                ('vars', models.ManyToManyField(related_name='task_templates', to='core.Variable', verbose_name='Variables')),
            ],
            options={
                'permissions': (('view_task_template', 'View Task Template'),),
            },
        ),
    ]
