# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tasktemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(related_name='hosts', to='core.HostGroup'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='host',
            name='vars',
            field=models.ManyToManyField(related_name='hosts', to='core.Variable'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='vars',
            field=models.ManyToManyField(related_name='host_groups', to='core.Variable'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='host_groups',
            field=models.ManyToManyField(related_name='task_templates', to='core.HostGroup'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='hosts',
            field=models.ManyToManyField(related_name='task_templates', to='core.Host'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='playbook',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='vars',
            field=models.ManyToManyField(related_name='task_templates', to='core.Variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
