# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:40
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170320_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('item', models.CharField(blank=True, choices=[('task', 'task'), ('task_template', 'task_template')], max_length=100)),
                ('action', models.CharField(choices=[('update', 'update'), ('delete', 'delete'), ('create', 'create'), ('error', 'error'), ('other', 'other'), ('replay', 'replay'), ('run', 'run')], max_length=100)),
                ('object_id', models.IntegerField(null=True)),
            ],
            options={
                'permissions': (('view_log', 'View Log'),),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook', models.FilePathField()),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('stopped', 'stopped'), ('fail', 'fail'), ('wait', 'wait')], default='wait', max_length=100)),
                ('pid', models.IntegerField(null=True)),
                ('dc', models.DateTimeField(auto_now_add=True)),
                ('host_groups', models.ManyToManyField(related_name='tasks', to='core.HostGroup')),
                ('hosts', models.ManyToManyField(related_name='tasks', to='core.Host')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.TaskTemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('vars', models.ManyToManyField(related_name='tasks', to='core.Variable')),
            ],
            options={
                'permissions': (('view_task', 'View Task'), ('stop_task', 'Stop Task'), ('run_task', 'Run Task')),
                'ordering': ('-dc',),
            },
            bases=(core.models.TaskOperationsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('stopped', 'stopped'), ('fail', 'fail'), ('wait', 'wait')], max_length=100)),
                ('output', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('dc', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Task')),
            ],
            options={
                'permissions': (('view_task_log', 'View Task Log'),),
            },
        ),
    ]
