# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ('id',), 'permissions': (('view_task', 'View Task'), ('stop_task', 'Stop Task'), ('run_task', 'Run Task'))},
        ),
        migrations.AddField(
            model_name='task',
            name='verbose',
            field=models.CharField(choices=[('v', 'standard'), ('vv', 'detail'), ('vvv', 'very detail'), ('vvvv', 'all')], default='v', max_length=4),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='verbose',
            field=models.CharField(choices=[('v', 'standard'), ('vv', 'detail'), ('vvv', 'very detail'), ('vvvv', 'all')], default='v', max_length=4),
        ),
    ]
