# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ansible', max_length=255)),
            ],
            options={
                'permissions': (('view_ansible_user', 'View Ansible User'),),
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ('id',), 'permissions': (('view_task', 'View Task'), ('stop_task', 'Stop Task'), ('run_task', 'Run Task'))},
        ),
        migrations.AddField(
            model_name='task',
            name='ansible_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.AnsibleUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='ansible_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='core.AnsibleUser'),
            preserve_default=False,
        ),
    ]
