# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170329_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibleuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
