# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:44
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170405_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ('id',), 'permissions': (('view_task', 'View Task'), ('stop_task', 'Stop Task'), ('run_task', 'Run Task'), ('replay_task', 'Replay Task'))},
        ),
        migrations.AddField(
            model_name='variable',
            name='cipher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=core.models.EncryptedValueField(max_length=255),
        ),
    ]
