# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 15:55
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170405_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ('id',), 'permissions': (('view_task', 'View Task'), ('stop_task', 'Stop Task'), ('run_task', 'Run Task'), ('replay_task', 'Replay Task'))},
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='cron',
            field=core.models.CronField(blank=True, default='', help_text='Minute Hour Day Month Weekday', max_length=100),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='datetime_cron',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
