# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170510_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktemplate',
            old_name='datetime_cron',
            new_name='cron_dt',
        ),
    ]
