# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170519_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_cron_created',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
