# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170519_1752'),
        ('core', '0007_auto_20170510_1331'),
    ]

    operations = [
    ]
