# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20170520_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='address',
            field=models.CharField(max_length=256),
        ),
    ]
