# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170510_1344'),
        ('core', '0010_merge_20170520_1243'),
    ]

    operations = [
    ]
