# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170610_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansibleuser',
            options={'ordering': ('name',), 'permissions': (('view_ansible_user', 'View Ansible User'),)},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('name',), 'permissions': (('view_host', 'View Host'),)},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'ordering': ('name',), 'permissions': (('view_host_group', 'View Host Groups'),)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ('id',), 'permissions': (('view_task', 'View Task'), ('stop_task', 'Stop Task'), ('run_task', 'Run Task'), ('replay_task', 'Replay Task'), ('inventory_task', 'View Task Inventory'))},
        ),
        migrations.AlterField(
            model_name='host',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
