# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170623_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause', models.IntegerField(help_text='Time in minutes')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_task', to='core.TaskTemplate')),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_cron_created',
            new_name='is_created_automatically',
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_number',
            field=models.IntegerField(null=True),
        ),
    ]
