# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170623_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='repeat_iter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='repeattask',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeat_task', to='core.TaskTemplate'),
        ),
    ]
