# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170705_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='users',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
