# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_host_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='users',
            field=models.CharField(blank=True, max_length=255, verbose_name='Users with an access to this host'),
        ),
    ]
