# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-14 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20180212_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='users',
        ),
        migrations.AddField(
            model_name='host',
            name='users',
            field=models.ManyToManyField(related_name='hosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
