# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-25 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180214_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='inventory',
            field=models.FileField(blank=True, null=True, upload_to='inventories'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='inventory',
            field=models.FileField(blank=True, null=True, upload_to='inventories'),
        ),
        migrations.AlterField(
            model_name='host',
            name='users',
            field=models.ManyToManyField(help_text='Users with an access to this host', related_name='hosts', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
