IN_PROGRESS = 'in_progress'
COMPLETED = 'completed'
STOPPED = 'stopped'
FAIL = 'fail'
WAIT = 'wait'

STATUSES = [IN_PROGRESS, COMPLETED, STOPPED, FAIL, WAIT]
STATUS_CHOICES = [(status, status) for status in STATUSES]
NOT_RUN_STATUSES = [COMPLETED, STOPPED, FAIL]
RUN_STATUSES = [IN_PROGRESS, WAIT]


TASK = 'task'
TASK_TEMPLATE = 'task_template'

ACTION_RUN = 'run'
ACTION_CREATE = 'create'
ACTION_DELETE = 'delete'
ACTION_UPDATE = 'update'
ACTION_REPLAY = 'replay'
ACTION_OTHER = 'other'
ACTION_COMPLETE = 'complete'
ACTION_STOP = 'stop'
ACTION_START = 'start'
ACTION_ERROR = 'error'

ACTIONS = [ACTION_UPDATE, ACTION_DELETE, ACTION_CREATE, ACTION_ERROR, ACTION_OTHER, ACTION_REPLAY, ACTION_RUN]
